In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
df = pd.read_csv("HousingData.csv")

In [4]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90    NaN  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99    NaN  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [5]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [6]:
df.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273     21.0   

          B  LSTAT  MEDV  
501  391.99    NaN  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lr = LinearRegression()

In [9]:
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [12]:
x = df.iloc[0:,0:-1]

In [13]:
y = df.iloc[0:,-1]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [16]:
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pred = lr.predict(x_test)

In [18]:
y_pred

array([25.61333139, 14.47563747,  9.93433745, 22.86170035, 35.30370352,
       10.17105712, 22.35108794, 28.22759846, 25.14266641, 22.89538501,
       40.04026073, 15.98618299,  9.80688024, 18.69960704, 32.39959719,
       29.00243461, 21.70993531, 20.99700848, 13.86224135, 21.35731235,
       24.80678193, 30.5030528 , 17.4058969 , 22.27003133, 20.01660988,
       24.15547634, 24.29888514, 22.56088006, 22.57598497, 11.20742431,
       36.60446572, 22.05794173, 39.49000823, 15.87638363, 12.26969468,
       18.77688471, 13.506067  , 35.16278022, 14.79646378, 32.50202731,
       30.42608416, 18.49145893, 25.82625983, 23.39181157, 28.64763849,
       14.47588112, 18.68439052, 26.48918783, 17.67608703, 16.12692107,
       17.13559132, 21.44825578, 17.55802181, 21.24636737, 15.73020776,
       30.09313358, 18.67002158, 15.1151743 , 20.54510698, 39.00839816,
       42.58536753, 34.13546982, 26.29743625, 21.91051614, 17.25628266,
       13.39942515, -2.4666427 , 22.33920416, 13.91144698,  8.69

In [19]:
y_test

213    28.1
346    17.2
405     5.0
38     24.7
279    35.1
       ... 
387     7.4
496    19.7
357    21.7
106    19.5
317    19.8
Name: MEDV, Length: 119, dtype: float64

In [20]:
meanSquaredError = np.mean((y_pred-y_test)**2)

In [21]:
meanSquaredError

17.85635758064901

In [22]:
from sklearn.preprocessing import PolynomialFeatures

In [23]:
polyFeature = PolynomialFeatures(degree=2)

In [24]:
x_train_poly = polyFeature.fit_transform(x_train)

In [25]:
x_test_poly = polyFeature.fit_transform(x_test)

In [26]:
polymodel = LinearRegression()

In [27]:
polymodel.fit(X=x_train_poly,y=y_train)

LinearRegression()

In [28]:
y_pred_poly = polymodel.predict(x_test_poly)

In [29]:
y_pred_poly

array([ 24.5727818 ,  20.18816662, -12.24224401,  21.45914698,
        35.43119574,  27.78091455,  11.01368785,  30.73848891,
        10.93660355,  18.87489247,  46.15786958,  15.77394009,
        14.32488799,  17.07316494,  61.53858042,  21.94696999,
        18.6728816 ,  25.0583663 ,  12.03145123,  21.54253888,
        21.0921185 ,  25.97985435,  24.61611152,  26.29371905,
        19.05551577,  27.34779286,  24.16351795,  25.1734457 ,
        20.04177237,  12.88448381,  32.95800447,  19.78734684,
        44.82627773,  15.95272303,  11.45193553,  17.94344211,
        11.28098989,  30.00307989,  12.24904203,  32.86048627,
        29.67793703,  16.79648995,  22.37242985,  20.67790627,
        29.81828737,  11.62891984,  17.79168129,  27.29161334,
        18.08081841,  19.23158097, -10.55372906,  18.16513395,
        16.04109335,  20.16484284,  14.5917058 ,  36.79283428,
        32.06286311,  22.12503862,  22.03390479,  42.39383531,
        48.08055449,  29.4259088 ,  27.88075924,  19.13

In [30]:
meanSquaredError2 = np.mean((y_pred_poly-y_test)**2)

In [31]:
meanSquaredError2

25.631591317338742

In [32]:
from sklearn.linear_model import Ridge 

In [33]:
rm = Ridge(alpha = 1)

In [34]:
rm.fit(x_train,y_train)

Ridge(alpha=1)

In [35]:
y_pred_rm = rm.predict(x_test)

In [36]:
y_pred_rm

array([25.57701115, 14.62107678, 10.66146713, 23.14898062, 34.82434731,
        9.20590289, 24.15115783, 28.22608431, 24.40357892, 22.83963902,
       39.57610137, 16.60268896,  9.8567591 , 19.67175348, 32.11727529,
       28.59673352, 21.04856857, 20.72915588, 13.9502621 , 20.54146988,
       24.50313159, 30.26048522, 16.98135623, 22.02979918, 19.39271726,
       23.57566926, 24.48165382, 23.03611201, 22.24938252, 10.48105862,
       37.12776532, 21.38214962, 39.2188127 , 15.94804355, 12.29920588,
       19.39935877, 13.61635745, 35.5881112 , 15.1294015 , 32.24522382,
       29.99988558, 18.92956329, 25.44358296, 22.80520438, 28.96780437,
       14.72916272, 18.45865458, 26.33661315, 18.10975863, 16.3633628 ,
       18.20934814, 21.9877135 , 18.03447612, 22.28011772, 15.95453183,
       30.41306701, 19.6897016 , 15.26961549, 21.07696445, 39.29588419,
       42.25885219, 34.53977022, 25.92167742, 22.65872074, 16.68194074,
       13.90335772, -2.53695826, 21.48098561, 12.8801746 ,  9.12

In [37]:
meanSquaredError3 = np.mean((y_pred_rm-y_test)**2)

In [38]:
meanSquaredError3

18.084077541962653

In [39]:
from sklearn.linear_model import Lasso 

In [42]:
lasso = Lasso(alpha = 1)

In [43]:
lasso.fit(x_train,y_train)

Lasso(alpha=1)

In [44]:
y_pred_lasso = lasso.predict(x_test)

In [45]:
meanSquaredError6 = np.mean((y_pred_lasso-y_test)**2)

In [46]:
meanSquaredError6

22.85682710063595